/ml_vision_node:
  ros__parameters:
    ml_rescue_debug: true

/front_camera:
  camera_node:
    ros__parameters:
      camera: 0
      role: 'viewfinder'
      format: 'BGR888'
      width: 1536
      height: 864
      sensor_mode: '2304:1296'
      orientation: 180