# docker-compose.yaml

version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev

    volumes:
      - ./src:/app/src
      - ./models:/app/models
      - ./calibration_images:/app/calibration_images
      - ./output:/app/output

    stdin_open: true
    tty: true
