name: ROS2 Tests

on: [push, pull_request]

jobs:
  build_and_test:
    if: github.repository == 'Wet-Lettuce-Robocup/toby-software-rescue'
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-noble-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Build and run tests
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          package-name: ml_rescue
          target-ros2-distro: kilted
